#include "AppFileTable.hpp"

#include "logger/Logger.hpp"

#include <cstring>

static logger::Logger log{AppFileTable::TAG};

// ------------------------------------------------------------
// Linker symbols generated by EMBED_FILES in main/CMakeLists.txt
//
// Symbol naming rule: for a file listed in EMBED_FILES as
//   <component_dir>/app_files/files/app_index.html
// ESP-IDF generates:
//   _binary_app_index_html_start
//   _binary_app_index_html_end
//
// Add a pair of extern declarations here for every file in
// main/app_files/files/.
// ------------------------------------------------------------

extern const uint8_t _binary_app_index_html_start[] asm("_binary_app_index_html_start");
extern const uint8_t _binary_app_index_html_end[]   asm("_binary_app_index_html_end");

extern const uint8_t _binary_styles_css_start[]     asm("_binary_styles_css_start");
extern const uint8_t _binary_styles_css_end[]       asm("_binary_styles_css_end");

extern const uint8_t _binary_app_js_start[]         asm("_binary_app_js_start");
extern const uint8_t _binary_app_js_end[]           asm("_binary_app_js_end");

extern const uint8_t _binary_favicon_ico_start[]    asm("_binary_favicon_ico_start");
extern const uint8_t _binary_favicon_ico_end[]      asm("_binary_favicon_ico_end");

// ------------------------------------------------------------
// File table — entries use the full request URL path.
// EmbeddedFileHandler is mounted at "/" with no prefix stripping,
// so paths here must match the URL exactly as the browser requests it.
// ------------------------------------------------------------

namespace {
struct FileEntry {
    const char*    path;
    const uint8_t* start;
    const uint8_t* end;
};

static const FileEntry files[] = {
    {"/app/ui/index.html", _binary_app_index_html_start, _binary_app_index_html_end},
    {"/app/ui/styles.css", _binary_styles_css_start,     _binary_styles_css_end},
    {"/app/ui/app.js",     _binary_app_js_start,         _binary_app_js_end},
    {"/favicon.ico",       _binary_favicon_ico_start,    _binary_favicon_ico_end},
};
} // anonymous namespace

// ------------------------------------------------------------
// AppFileTable implementation
// ------------------------------------------------------------

const framework_files::EmbeddedFile* AppFileTable::find(std::string_view path) const {
    log.debug("find '%.*s'", (int)path.size(), path.data());

    for (const auto& entry : files) {
        if (path == entry.path) {
            static framework_files::EmbeddedFile result;
            result.data = entry.start;
            result.size = entry.end - entry.start;
            return &result;
        }
    }

    log.debug("not found: '%.*s'", (int)path.size(), path.data());
    return nullptr;
}

const uint8_t* AppFileTable::find(const char* path, size_t& outSize) const {
    for (const auto& entry : files) {
        if (std::strcmp(entry.path, path) == 0) {
            outSize = entry.end - entry.start;
            return entry.start;
        }
    }
    return nullptr;
}
